// <auto-generated />
using MEDSys.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MEDSys.Api.Migrations
{
    [DbContext(typeof(AppointmentContext))]
    [Migration("20180403214851_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MEDSys.Api.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClientBirthday");

                    b.Property<string>("ClientLastName");

                    b.Property<string>("ClientName");

                    b.Property<string>("ServiceLine");

                    b.Property<DateTime>("ServiceLineEndDate");

                    b.Property<DateTime>("ServiceLineStartDate");

                    b.Property<string>("StaffLastName");

                    b.Property<string>("StaffName");

                    b.Property<string>("StaffSpecialty");

                    b.HasKey("AppointmentID");

                    b.ToTable("Appointment");
                });
#pragma warning restore 612, 618
        }
    }
}
